[package]
edition = "2021"
name = "rust-journal"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
home = "0.5"
serde_json = "1.0"
structopt = "0.3"

[dependencies.serde]
features = ["derive"]
version = "1.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4"
